var firstname;
var lastname;
var age;
var address;
var dateOfBirth;
firstname='Árpita';
lastname='Deb';
age='27';
address='Saskatoon';
dateOfBirth='10/23/1990';
console.log('firstname: ',firstname);
console.log('lstname: ',lastname);
console.log('age: ',age);
console.log('address: ',address);
console.log('dateOfBirth: ',dateOfBirth);